### ISSUE TITLE
Deprecation of extra user field #14 

### ISSUE THREAD

**Issue by TubsDK** [praxisdigital/moodle-local_augmented_teacher#11]
**Describe the bug**
A internal api has been deprecated: 
![image](https://github.com/user-attachments/assets/b54b4e2f-6390-4994-8522-540dcb068179)

**To Reproduce**
1. Open argumented teacher. 
2. Choose task "Send merge messages" 
3. See error

**Current behavior**
An error is displayed

**Expected behavior**

**Ticket link**

**Related issues**

**Comment by AraPraxis** [comment]
## Changes
- Fixed moodle deprecations

## Test
- That the plugin works as expected

## Info
PR: https://github.com/praxisdigital/moodle-local_augmented_teacher/pull/12
Branch: ara_GH-11_42
Moodle: 4.2+

Notice that later on only the MOODLE_42_STABLE should be used after merging, because of the deprecations...

**Comment by AraPraxis** [comment]
Show and tell with Tue (Approved)

**Comment by AraPraxis** [comment]
It has been merged into our fork and smartlearning's master branch - We should use smartlearning's when updating, which means;

All sites should be MOVED from this plugin https://morris.praxis.dk/plugin/578

To this plugin https://morris.praxis.dk/plugin/187

**NOTE** that there are tables installed for this plugin, and the plugin should therefore not be uninstalled and installed again, but moved carefully..


All sites on /plugin/187 should have the newest release
Branch: master
Version: 2024101700
Commit: 5ddab4290b6b5899538142cee175c7ec2d104f0a
